package org.primejava.cms.model;

// Generated 2014-8-5 9:56:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * BaseContents generated by hbm2java
 */
@Entity
@Table(name = "t_contents")
public class Contents implements java.io.Serializable {

    private String id;
    private String  content;
    private Integer version;

    @Id
    @Column(name = "ID", updatable = false, length = 36)
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "CONTENT")
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 版本号(乐观锁)
     */
    @Version
    @Column(name = "VER")
    public Integer getVersion() {
        return version;
    }

    /**
     * 设置 版本号(乐观锁)
     * @param version
     *            版本号(乐观锁)
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

}
