package org.primejava.cms.model;

// Generated 2014-7-23 8:54:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DicCommons generated by hbm2java
 */
@Entity
@Table(name = "DIC_COMMONS")
public class DictionaryCommons implements java.io.Serializable {

    private String  id;
    private String  code;
    private String  value;
    private Boolean preset;
    private String  comKey;

    public DictionaryCommons() {
    }

    public DictionaryCommons(String id) {
        this.id = id;
    }

    public DictionaryCommons(String id, String code, String value) {
        this.id = id;
        this.code = code;
        this.value = value;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "CODE", length = 18)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "VALUE")
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "PRESET")
    public Boolean getPreset() {
        return preset;
    }

    public void setPreset(Boolean preset) {
        this.preset = preset;
    }

    @Column(name = "COM_KEY")
    public String getComKey() {
        return comKey;
    }

    public void setComKey(String comKey) {
        this.comKey = comKey;
    }

}
