
package org.primejava.cms.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserWebServiceImplService", targetNamespace = "http://impl.webservice.cms.primejava.org/", wsdlLocation = "http://127.0.0.1:8081/oa-web/webservice/userWs?wsdl")
public class UserWebServiceImplService
    extends Service
{

    private final static URL USERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USERWEBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.cms.primejava.org/", "UserWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8081/oa-web/webservice/userWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USERWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UserWebServiceImplService() {
        super(__getWsdlLocation(), USERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public UserWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public UserWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServiceImplPort")
    public UserWebService getUserWebServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.cms.primejava.org/", "UserWebServiceImplPort"), UserWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServiceImplPort")
    public UserWebService getUserWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.cms.primejava.org/", "UserWebServiceImplPort"), UserWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw USERWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
