package org.primejava.cms.imp.pojo;

// Generated 2014-7-23 8:54:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DicCommons generated by hbm2java
 */
@Entity
@Table(name = "DIC_RELEVANCE_TABLE_FIELD")
public class RelevanceTableField implements java.io.Serializable {

    private String id;
    private String table;
    private String relevanceTable;
    private String tableField;
    private String relevanceTableField;

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "TABLE_NAME")
    public String getTable() {
        return table;
    }

    public void setTable(String table) {
        this.table = table;
    }

    @Column(name = "RELEVANCE_TABLE")
    public String getRelevanceTable() {
        return relevanceTable;
    }

    public void setRelevanceTable(String relevanceTable) {
        this.relevanceTable = relevanceTable;
    }

    @Column(name = "TABLE_FIELD")
    public String getTableField() {
        return tableField;
    }

    public void setTableField(String tableField) {
        this.tableField = tableField;
    }

    @Column(name = "RELEVANCE_TABLE_FIELD")
    public String getRelevanceTableField() {
        return relevanceTableField;
    }

    public void setRelevanceTableField(String relevanceTableField) {
        this.relevanceTableField = relevanceTableField;
    }

}
